### ISSUE TITLE
FormList with search 

### ISSUE THREAD

**Issue by GGZORR** [PrioritySoftware/priority-ionic#1]
Hi,
I need a form list with a search bar - the form list results need to change while typing (like a combo).
Is there component that do so or example ? 

Thanks.

**Comment by naomipol** [comment]
To implement a client side search on the form list records, you could apply a `Filter` @Input to the `form-list` element that will contain the search string for each column the search should effect. see the [docs](https://prioritysoftware.github.io/priority-ionic/Components/FormList)

Here is an example:

To implement a search for the ORDERS form by the customer name or order number apply the following filter:

```js

let query = ""; //bind with ngModel to your search input.
let filter = [{column: 'CUSTDES', value: this.query, type: 'startWith'},
              {column: 'ORDNAME', value: this.query, type: 'startWith'}]
```

And then apply to the `form-list`:

```html

<form-list [Form]="form" ... [Filter]="filter"></form-list>

**Comment by idokislev** [comment]
הי,

תוכלי להסיר אותי מרשימת התפוצה?

תודה,
עידו

בתאריך 27 ביוני 2017 4:43 אחה״צ,‏ GGZORR <notifications@github.com> כתב:

Hi,
I need a form list with a search bar - the form list results need to change while typing (like a combo).
Is there component that do so or example ?

Thanks.

**Comment by neomib** [comment]
Closing this issue. This is not the place for such questions. If you have a 'how can i do something' question please ask at stackoverflow!
