### ISSUE TITLE
Update Field is not working without assigning key to active new  row

### ISSUE THREAD

**Issue by OlegMedatech** [PrioritySoftware/priority-ionic#3]
Update Field did not worked automatically as expected in new row.
Temporally solution what set row index to selected item in constructor.

 this.selectedItem = this.formService.getFormRow(this.form, this.rowInd);    
 this.selectedItem.key=this.rowInd;

**Comment by neomib** [comment]
Thanks! It will be fixed in the next version 1.0.6
