### ISSUE TITLE
When trying to get companies there are exception: errType is not defined at InvokeError_0 

### ISSUE THREAD

**Issue by OlegMedatech** [PrioritySoftware/priority-ionic#4]
I am trying to add switch company functionality to my application on 
ionViewDidLoad of my page I run flowing function:

 getCompanies(): Promise<any>
    {
        return new Promise((resolve, reject) =>
        {
            this.configService.getCompanies()
                .then(
                (companies: Company[]) =>
                {
                    resolve(companies);
                },
                (reason: ServerResponse) =>
                {
                    if (reason.code === ServerResponseCode.NotSupport)
                    {
                        this.supportCompanySelection = false;
                    }
                    alert('getCompanies reason' + reason);
                    reject(reason);
                }
                ).catch((reason) => {   alert('getCompanies catch' + reason); reject(reason) });
        });
    }

On debug I see the flowing Exception in ConfigurationService, getCompanies function:

![image](https://user-images.githubusercontent.com/31067522/30001321-e079969e-9092-11e7-8014-d3bb7c3591f3.png)

**Comment by neomib** [comment]
Hi,
This bug will be fixed in the next version 1.0.8. But I can tell you now it means that your Priority version is lower than 18.0.1. This method is only supported in Priority version 18.0.1 or higher.
